[Dynamic Neighbor]: add patch to support dynamic neighbor configuration.
sonic-net/sonic-quagga pull request #14
Opened 2017-06-09 19:29 UTC by sihuihan88

2017-06-09 19:29 UTC, msftclas commented
@sihuihan88,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-06-09 19:36 UTC, pavel-shirshov requested changes

2017-06-09 19:36 UTC, pavel-shirshov commented on bgpd/bgp_fsm.c
> +
The same code 4 times. Probably it's better to introduce a static function here?

2017-06-09 19:36 UTC, pavel-shirshov commented on bgpd/bgp_network.c
> +
Probably it's better to remove it?

2017-06-10 00:11 UTC, stcheng commented
could you provide the patch info you reference? Add it to the commit message and also state what you have changed due to the patch conflicts.

2017-06-12 18:25 UTC, sihuihan88 commented on bgpd/bgp_fsm.c
> +
The code is used to provide log info if debug_event is enabled. They are not exactly the same. So adding more detailed log info now for better troubleshooting.

2017-06-12 18:25 UTC, sihuihan88 commented on bgpd/bgp_network.c
> +
Good catch. Have updated accordingly.

2017-06-13 09:23 UTC, lguohan commented
can you check this commit? https://github.com/FRRouting/frr/commit/20eb8864bbaf19771502b6c1ed3f1e43186f97eb

2017-06-13 09:24 UTC, lguohan commented
and this one. https://github.com/FRRouting/frr/commit/57e9ee0a9430e0fa0c7fe0751eaf0129abb7fa9c

2017-06-13 09:25 UTC, lguohan commented
and this one https://github.com/FRRouting/frr/commit/2aab8d2b2cd88163d48317224635c90f0dd3a50d

2017-06-16 05:04 UTC, lguohan commented on bgpd/bgp_fsm.c
> +          zlog_debug("BGP stop: %s (dynamic neighbor) deleted", peer->host);
-> zlog_info

check line 467: neighbor down event is logged as info level, this is also neighbor down event, should also logged as info level.

2017-06-16 05:08 UTC, lguohan commented
next time, you need to do a fork and https://help.github.com/articles/fork-a-repo/

2017-06-16 06:42 UTC, lguohan commented on bgpd/bgp_fsm.c
> +
I think this logic can be merged into bgp_stop() as bgp_stop already has similar logic. We should enable code re-use.

2017-06-16 06:43 UTC, lguohan commented on bgpd/bgp_fsm.c
> +    }
should move into bgp_stop()

2017-06-16 06:43 UTC, lguohan commented on bgpd/bgp_fsm.c
> +   }
move into bgp_stop().

2017-06-16 07:13 UTC, lguohan commented on bgpd/bgpd.c
> +  }
this is neighbor add event, I think it should be info level, we should print it out when we enabled log neighbor change.

2017-06-16 07:15 UTC, lguohan commented on bgpd/bgpd.c
> +  }
we should do something simliar here.

      /* bgp log-neighbor-changes of neighbor Down */
      if (bgp_flag_check (peer->bgp, BGP_FLAG_LOG_NEIGHBOR_CHANGES))
 zlog_info ("%%ADJCHANGE: neighbor %s Down %s", peer->host,
                   peer_down_str [(int) peer->last_reset]);

2017-06-16 07:21 UTC, lguohan requested changes
mostly logging information related

2017-06-17 01:47 UTC, lguohan approved these changes

2017-06-19 15:41 UTC, pavel-shirshov approved these changes

2017-06-19 17:46 UTC, merged