Add 'set src <ipv6>' functionality for route-maps
sonic-net/sonic-quagga pull request #4
Opened 2016-10-28 20:47 UTC by pavel-shirshov

Also was added two commands:
show ipv6 protocol
ipv6 protocol route-map

2016-10-28 21:06 UTC, qiluo-msft commented on lib/if.h
> +extern struct interface *if_lookup_exact_address6 (struct in6_addr src);
> src [](start = 66, length = 4)

remove parameter name as others. #Closed

2016-10-28 21:15 UTC, qiluo-msft commented on zebra/zebra_routemap.c
> +       "set src (A.B.C.D|X:X::X:X)",
>X:X::X:X [](start = 25, length = 8)

A:B:C:D:E:F:G:H ?

2016-10-28 21:17 UTC, qiluo-msft commented on zebra/zebra_routemap.c
> +  int is_ipv4;
>int [](start = 2, length = 3)

bool ?

2016-10-28 21:18 UTC, qiluo-msft commented on zebra/zebra_routemap.c
> +  is_ipv4 = inet_pton(AF_INET, argv[0], &src) > 0 ? 1 : 0;
> ? 1 : 0 [](start = 50, length = 7)

remove " ? 1 : 0" #Closed

2016-10-28 21:22 UTC, qiluo-msft commented on zebra/zebra_routemap.c
> +      if (!pif)
>if (!pif) [](start = 6, length = 9)

Move outside the outer if block?

2016-10-28 21:22 UTC, qiluo-msft commented on zebra/zebra_routemap.c
> +       "no set src (A.B.C.D|X:X::X:X)",
>X:X::X:X [](start = 28, length = 8)

The same

2016-10-28 21:28 UTC, qiluo-msft commented on zebra/zebra_rib.c
> +  if (src)
>if (src) [](start = 2, length = 8)

remove?

2016-10-28 21:31 UTC, qiluo-msft requested changes
As comments

2016-10-31 20:02 UTC, pavel-shirshov commented on zebra/zebra_routemap.c
> +       "set src (A.B.C.D|X:X::X:X)",
It's a special parameter inside of quagga. Check https://github.com/Azure/sonic-quagga/blob/debian/0.99.24.1/lib/command.h#L264

2016-10-31 20:05 UTC, pavel-shirshov commented on zebra/zebra_routemap.c
> +  int is_ipv4;
There're no bool type in the whole quagga codebase.
So I decided use their conventions.

2016-10-31 20:06 UTC, pavel-shirshov commented on zebra/zebra_routemap.c
> +       "no set src (A.B.C.D|X:X::X:X)",
It's a special parameter inside of quagga. Check https://github.com/Azure/sonic-quagga/blob/debian/0.99.24.1/lib/command.h#L264

2016-10-31 20:09 UTC, pavel-shirshov commented on zebra/zebra_routemap.c
> +      if (!pif)
can you please explain it more?

2016-10-31 20:11 UTC, pavel-shirshov commented on zebra/zebra_rib.c
> +  if (src)
In this case the following line will cause a crash
https://github.com/Azure/sonic-quagga/blob/pavelsh/src/zebra/zebra_rib.c#L2963

2016-11-01 23:39 UTC, qiluo-msft commented on zebra/zebra_routemap.c
> +      if (!pif)
if (is_ipv4) pif = ...
else pif = ...

if (!pif)
{
}

---
In reply to: [85822103](https://github.com/Azure/sonic-quagga/pull/4#discussion_r85822103) [](ancestors = 85822103)

2016-11-01 23:40 UTC, qiluo-msft requested changes
as comments.

2016-11-02 00:52 UTC, pavel-shirshov commented on zebra/zebra_rib.c
> +  if (src)
In this case the following line will cause a crash
[https://github.com/Azure/sonic-quagga/blob/pavelsh/src/zebra/zebra_rib.c#L2963](https://github.com/Azure/sonic-quagga/blob/pavelsh/src/zebra/zebra_rib.c#L2963)

---
In reply to: [85613447](https://github.com/Azure/sonic-quagga/pull/4#discussion_r85613447) [](ancestors = 85613447)

2016-11-02 00:53 UTC, qiluo-msft commented on zebra/zebra_rib.c
> +  if (src)
I see. Then
if (src == NULL) nexthop->src.ipv6 = all_zero_address

2016-11-02 02:04 UTC, pavel-shirshov commented on zebra/zebra_rib.c
> +  if (src)
Check this function from quagga nexthop_ipv4_ifindex_add(). I copied my ipv6 function from this.

---
In reply to: [86056451](https://github.com/Azure/sonic-quagga/pull/4#discussion_r86056451) [](ancestors = 86056451)

2016-11-02 15:26 UTC, lguohan commented on zebra/rt_netlink.c
>          addattr_l (&req.n, sizeof req, RTA_PREFSRC, &src->ipv4, bytelen);
is this correct? only for ipv4? I noticed that you have modified the build_multipath for v6, but however, I feel ipv6 is missing here. #Resolved

2016-11-02 18:48 UTC, pavel-shirshov commented on zebra/rt_netlink.c
>          addattr_l (&req.n, sizeof req, RTA_PREFSRC, &src->ipv4, bytelen);
This code should work only for multipath case.
I don't have anything related ipv6 multipath in the codebase yet.
But I could add this into the code. It doesn't matter, honestly.

---
In reply to: [86168202](https://github.com/Azure/sonic-quagga/pull/4#discussion_r86168202) [](ancestors = 86168202)

2016-11-03 13:29 UTC, lguohan reviewed
I raised one question w.r.t. to the src.

2016-11-03 13:30 UTC, lguohan approved these changes

2016-11-03 17:59 UTC, merged